#!/usr/bin/env python3
"""
Strict BTT (Branching Tree Technique) rule checker for Solidity test suites.

This script enforces BTT best practices including:
- Tree-to-test synchronization via bulloak
- Orphan test detection (tests without tree branches)
- Specific error selectors in revert expectations
- No assertions in modifiers
- No loops in tests (one leaf = one test)
- README synchronization
- And more...

Usage:
    python tool/btt_check.py [--skip-bulloak] [--verbose]
"""
import argparse
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Set, Tuple

ROOT = Path(__file__).resolve().parents[1]
BTT_DIR = ROOT / "test" / "btt"
README_PATH = BTT_DIR / "README.md"

# Assertion patterns that indicate a test is actually testing something
ASSERT_PATTERNS = [
    r"\bassert\w*\s*\(",
    r"\bvm\.expectRevert\s*\(",
    r"\bvm\.expectEmit\b",
    r"\bexpectEmit\b",
    r"\bassertTrue\b",
    r"\bassertFalse\b",
    r"\bassertEq\b",
    r"\bassertGt\b",
    r"\bassertGe\b",
    r"\bassertLt\b",
    r"\bassertLe\b",
    r"\brevert\s*\(",
]
ASSERT_RE = re.compile("|".join(ASSERT_PATTERNS))

# Patterns for detecting issues
EXPECT_REVERT_BARE_RE = re.compile(r"\bvm\.expectRevert\s*\(\s*\)\s*;", re.M)
BULLOAK_SEPARATOR_RE = re.compile(r"BULLOAK AUTOGENERATED SEPARATOR")
TODO_FIXME_RE = re.compile(r"\b(TODO|FIXME|XXX|HACK)\b", re.I)

# Tree parsing regex
TREE_NODE_RE = re.compile(r"^(?P<indent>[\s│]*)(?P<edge>├──|└──)\s+(?P<text>.*)$")



def fail(msg, errors):
    errors.append(msg)


def warn(msg, warnings):
    warnings.append(msg)


def strip_comments(s: str) -> str:
    s = re.sub(r"//.*", "", s)
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)
    return s


def iter_functions(text: str):
    i = 0
    while True:
        # Match function signature - use [^)]* for parameters to avoid matching past closing paren
        # Then match visibility, modifiers (anything except { and ;), and opening brace
        m = re.search(r"\bfunction\s+([A-Za-z0-9_]+)\s*\([^)]*\)\s*(?:external|public|internal|private|view|pure|payable|virtual|override|\s|[A-Za-z0-9_]+)*\{", text[i:], re.S)
        if not m:
            break
        name = m.group(1)
        start = i + m.start()
        brace_start = i + m.end() - 1
        depth = 0
        j = brace_start
        while j < len(text):
            if text[j] == '{':
                depth += 1
            elif text[j] == '}':
                depth -= 1
                if depth == 0:
                    break
            j += 1
        if depth != 0:
            i = brace_start + 1
            continue
        body = text[brace_start + 1:j]
        line = text[:start].count("\n") + 1
        yield name, body, line
        i = j + 1


def iter_modifiers(text: str):
    i = 0
    while True:
        m = re.search(r"\bmodifier\s+([A-Za-z0-9_]+)\s*\([^;]*\)\s*\{", text[i:], re.S)
        if not m:
            break
        name = m.group(1)
        start = i + m.start()
        brace_start = i + m.end() - 1
        depth = 0
        j = brace_start
        while j < len(text):
            if text[j] == '{':
                depth += 1
            elif text[j] == '}':
                depth -= 1
                if depth == 0:
                    break
            j += 1
        if depth != 0:
            i = brace_start + 1
            continue
        body = text[brace_start + 1:j]
        line = text[:start].count("\n") + 1
        yield name, body, line
        i = j + 1


def parse_tree_leaves(path: Path):
    nodes = []
    lines = path.read_text().splitlines()
    for idx, line in enumerate(lines):
        m = TREE_NODE_RE.match(line)
        if not m:
            continue
        indent = len(m.group("indent"))
        text = m.group("text").strip()
        nodes.append((idx, indent, text))

    leaves = []
    for i, (idx, indent, text) in enumerate(nodes):
        is_leaf = True
        for j in range(i + 1, len(nodes)):
            _, next_indent, _ = nodes[j]
            if next_indent <= indent:
                break
            is_leaf = False
            break
        if is_leaf:
            leaves.append((idx + 1, text))
    return leaves


def check_bulloak():
    if not shutil_which("bulloak"):
        return False, "bulloak not found in PATH"
    try:
        subprocess.check_call(["bulloak", "check", "test/btt/*.tree"], cwd=ROOT)
        return True, None
    except subprocess.CalledProcessError as e:
        return False, f"bulloak check failed: {e}"


def shutil_which(cmd):
    for p in os.environ.get("PATH", "").split(os.pathsep):
        candidate = Path(p) / cmd
        if candidate.exists() and os.access(candidate, os.X_OK):
            return str(candidate)
    return None


def get_tree_files_from_readme() -> Set[str]:
    """Extract tree file names mentioned in README.md table."""
    if not README_PATH.exists():
        return set()

    text = README_PATH.read_text()
    # Match patterns like `Kernel.execute.tree` or | Kernel.execute.tree |
    tree_files = set()
    for m in re.finditer(r"`?([A-Za-z0-9_]+\.[A-Za-z0-9_]+\.tree)`?", text):
        tree_files.add(m.group(1))
    return tree_files


def count_test_functions(text: str) -> dict:
    """Count occurrences of each test function name."""
    counts = {}
    for name, _, line in iter_functions(text):
        if name.startswith("test_"):
            if name not in counts:
                counts[name] = []
            counts[name].append(line)
    return counts


# =============================================================================
# ORPHAN TEST DETECTION HELPERS
# =============================================================================

def normalize_name(name: str) -> str:
    """Normalize a name for comparison (lowercase, remove underscores)."""
    return name.lower().replace("_", "")


def extract_key_words(name: str) -> Set[str]:
    """Extract significant words from a function name."""
    name = re.sub(r'^test_?', '', name, flags=re.I)
    words = re.findall(r'[A-Z][a-z]*|[a-z]+|\d+', name)
    stopwords = {'the', 'is', 'a', 'an', 'and', 'or', 'for', 'to', 'in', 'of', 'when', 'given', 'then'}
    return {w.lower() for w in words if len(w) > 2 and w.lower() not in stopwords}


def get_expected_functions_from_bulloak(tree_path: Path) -> Set[str]:
    """Run bulloak scaffold and extract expected function names."""
    try:
        result = subprocess.run(
            ["bulloak", "scaffold", str(tree_path), "--solidity-version", "^0.8.0"],
            capture_output=True,
            text=True,
            cwd=ROOT
        )
        function_names = set()
        for m in re.finditer(r"\bfunction\s+(test_[A-Za-z0-9_]+)\s*\(", result.stdout):
            function_names.add(m.group(1))
        return function_names
    except Exception:
        return set()


def get_sol_test_functions(sol_path: Path) -> List[Tuple[str, int]]:
    """Extract test function names from a .t.sol file."""
    text = sol_path.read_text()
    functions = []
    pattern = r"\bfunction\s+(test_[A-Za-z0-9_]+)\s*\("
    for m in re.finditer(pattern, text):
        name = m.group(1)
        line = text[:m.start()].count("\n") + 1
        functions.append((name, line))
    return functions


def find_matching_tree_file(sol_path: Path) -> Path | None:
    """Find the .tree file that corresponds to a .t.sol file."""
    stem = sol_path.stem
    if stem.endswith(".t"):
        tree_stem = stem[:-2]
        tree_path = sol_path.parent / f"{tree_stem}.tree"
        if tree_path.exists():
            return tree_path
    return None


def extract_abstract_contract_name(sol_path: Path) -> str | None:
    """Extract the abstract contract name from a .t.sol file."""
    text = sol_path.read_text()
    m = re.search(r"abstract\s+contract\s+([A-Za-z0-9_]+)\s+is", text)
    if m:
        return m.group(1)
    return None


def find_tree_by_contract_name(contract_name: str) -> Path | None:
    """Find a .tree file by its contract name (first line)."""
    for tree_path in BTT_DIR.glob("*.tree"):
        first_line = tree_path.read_text().splitlines()[0].strip()
        if first_line == contract_name:
            return tree_path
    return None


def is_function_in_tree(func_name: str, expected_functions: Set[str]) -> bool:
    """Check if a function name matches any expected function from the tree."""
    normalized = normalize_name(func_name)

    # Direct match (normalized)
    if any(normalize_name(exp) == normalized for exp in expected_functions):
        return True

    # Extract key words from actual function
    actual_words = extract_key_words(func_name)
    if not actual_words:
        return False

    for expected in expected_functions:
        expected_words = extract_key_words(expected)

        # Check if actual words are a substantial subset of expected words
        common = actual_words & expected_words
        if len(common) >= len(actual_words) * 0.6:
            return True
        if len(common) >= len(expected_words) * 0.6:
            return True

        # Check normalized string containment
        norm_actual = normalize_name(func_name)
        norm_expected = normalize_name(expected)

        if norm_actual in norm_expected or norm_expected in norm_actual:
            return True

        # Check prefix match with some tolerance
        min_len = min(len(norm_actual), len(norm_expected))
        if min_len > 20:
            if norm_actual[:min_len-10] == norm_expected[:min_len-10]:
                return True

    return False


def check_orphan_tests() -> Dict[Path, List[Tuple[str, int]]]:
    """Check for test functions that don't have corresponding tree leaves."""
    orphans: Dict[Path, List[Tuple[str, int]]] = {}

    for sol_path in sorted(BTT_DIR.glob("*.t.sol")):
        # Find matching tree file
        tree_path = find_matching_tree_file(sol_path)
        if not tree_path:
            contract_name = extract_abstract_contract_name(sol_path)
            if contract_name:
                tree_path = find_tree_by_contract_name(contract_name)

        if not tree_path:
            continue

        # Get expected function names from bulloak scaffold
        expected_functions = get_expected_functions_from_bulloak(tree_path)
        if not expected_functions:
            continue

        # Get actual test functions from .t.sol
        actual_functions = get_sol_test_functions(sol_path)

        # Find orphans
        file_orphans = []
        for func_name, line_num in actual_functions:
            if func_name.startswith("test_receive_"):
                continue
            if func_name in ("test_setUp",):
                continue

            if not is_function_in_tree(func_name, expected_functions):
                file_orphans.append((func_name, line_num))

        if file_orphans:
            orphans[sol_path] = file_orphans

    return orphans


def main():
    parser = argparse.ArgumentParser(description="Strict BTT rule checker")
    parser.add_argument("--skip-bulloak", action="store_true", help="skip bulloak check")
    parser.add_argument("--verbose", "-v", action="store_true", help="show warnings too")
    args = parser.parse_args()

    errors = []
    warnings = []

    # ==========================================================================
    # RULE 1: Bulloak check must pass (tree-to-test synchronization)
    # ==========================================================================
    if not args.skip_bulloak:
        ok, msg = check_bulloak()
        if not ok:
            fail(f"bulloak: {msg}", errors)

    # ==========================================================================
    # RULE 2: No bulloak separators in final code
    # ==========================================================================
    for path in BTT_DIR.rglob("*"):
        if path.is_file() and path.suffix in {".t.sol", ".tree"}:
            text = path.read_text()
            if BULLOAK_SEPARATOR_RE.search(text):
                fail(f"bulloak separator present: {path.relative_to(ROOT)}", errors)

    # ==========================================================================
    # RULE 3: Tree leaves must be specific (no vague "it should revert")
    # ==========================================================================
    vague_leaf_re = re.compile(r"^it should revert\.?$", re.I)
    vague_revert_re = re.compile(r"it should revert", re.I)
    for tree_path in BTT_DIR.glob("*.tree"):
        leaves = parse_tree_leaves(tree_path)
        for line, text in leaves:
            if vague_leaf_re.match(text) or (vague_revert_re.search(text) and "with" not in text.lower()):
                fail(f"vague leaf in {tree_path.relative_to(ROOT)}:{line}: '{text}'", errors)

    # ==========================================================================
    # RULE 4: No bare vm.expectRevert() - must specify error selector
    # ==========================================================================
    for path in BTT_DIR.glob("*.t.sol"):
        text = path.read_text()
        if EXPECT_REVERT_BARE_RE.search(text):
            fail(f"bare vm.expectRevert() in {path.relative_to(ROOT)}", errors)

    # ==========================================================================
    # RULE 5: Modifiers cannot contain assertions (setup only)
    # ==========================================================================
    for path in BTT_DIR.glob("*.t.sol"):
        text = path.read_text()
        for name, body, line in iter_modifiers(text):
            body_no_comments = strip_comments(body)
            if ASSERT_RE.search(body_no_comments):
                fail(f"modifier contains assertion: {path.relative_to(ROOT)}:{line} {name}", errors)

    # ==========================================================================
    # RULE 6: Tests must assert something, no comment-only tests, no loops
    # ==========================================================================
    loop_re = re.compile(r"\b(for|while)\s*\(")
    for path in BTT_DIR.glob("*.t.sol"):
        text = path.read_text()
        for name, body, line in iter_functions(text):
            if not name.startswith("test_"):
                continue
            body_no_comments = strip_comments(body)
            if body_no_comments.strip() == "":
                fail(f"comment-only test: {path.relative_to(ROOT)}:{line} {name}", errors)
                continue
            if not ASSERT_RE.search(body_no_comments):
                fail(f"test has no assertions: {path.relative_to(ROOT)}:{line} {name}", errors)
            if loop_re.search(body_no_comments):
                fail(f"loop inside test: {path.relative_to(ROOT)}:{line} {name}", errors)

    # ==========================================================================
    # RULE 7: Every .tree file must have a corresponding .t.sol file
    # ==========================================================================
    for tree_path in BTT_DIR.glob("*.tree"):
        sol_path = tree_path.with_suffix(".t.sol")
        if not sol_path.exists():
            fail(f"missing test file for {tree_path.relative_to(ROOT)}: expected {sol_path.name}", errors)

    # ==========================================================================
    # RULE 8: Every .tree file should be listed in README.md
    # ==========================================================================
    readme_trees = get_tree_files_from_readme()
    for tree_path in BTT_DIR.glob("*.tree"):
        if tree_path.name not in readme_trees:
            warn(f"tree file not in README.md: {tree_path.name}", warnings)

    # ==========================================================================
    # RULE 9: No duplicate test function names within a file
    # ==========================================================================
    for path in BTT_DIR.glob("*.t.sol"):
        text = path.read_text()
        counts = count_test_functions(text)
        for name, lines in counts.items():
            if len(lines) > 1:
                fail(f"duplicate test function: {path.relative_to(ROOT)} {name} at lines {lines}", errors)

    # ==========================================================================
    # RULE 10: No TODO/FIXME in test function bodies (tests should be complete)
    # ==========================================================================
    for path in BTT_DIR.glob("*.t.sol"):
        text = path.read_text()
        for name, body, line in iter_functions(text):
            if not name.startswith("test_"):
                continue
            if TODO_FIXME_RE.search(body):
                warn(f"TODO/FIXME in test: {path.relative_to(ROOT)}:{line} {name}", warnings)

    # ==========================================================================
    # RULE 11: No orphan tests (tests must have corresponding tree branches)
    # ==========================================================================
    if not args.skip_bulloak:  # Only check if bulloak is available
        orphans = check_orphan_tests()
        for sol_path, funcs in orphans.items():
            for func_name, line_num in funcs:
                fail(f"orphan test (no tree branch): {sol_path.relative_to(ROOT)}:{line_num} {func_name}", errors)

    # ==========================================================================
    # OUTPUT RESULTS
    # ==========================================================================
    if args.verbose and warnings:
        print("WARNINGS:")
        for w in warnings:
            print(f"  - {w}")
        print()

    if errors:
        print("BTT CHECK FAILED")
        for e in errors:
            print(f"- {e}")
        sys.exit(1)

    print("BTT CHECK PASSED")
    if warnings and not args.verbose:
        print(f"({len(warnings)} warnings - use -v to see)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
