#!/usr/bin/env python3
"""
Strict BTT (Branching Tree Technique) rule checker for Solidity test suites.

This script enforces BTT best practices including:
- Tree-to-test synchronization via bulloak
- Orphan test detection (tests without tree branches)
- Specific error selectors in revert expectations
- No assertions in modifiers
- No loops in tests (one leaf = one test)
- And more...

Usage:
    python tool/btt_check.py [--skip-bulloak] [--verbose]
"""
import argparse
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Set, Tuple

ROOT = Path(__file__).resolve().parents[1]
BTT_DIR = ROOT / "test" / "btt"

# Assertion patterns that indicate a test is actually testing something
ASSERT_PATTERNS = [
    r"\bassert\w*\s*\(",
    r"\bvm\.expectRevert\s*\(",
    r"\bvm\.expectEmit\b",
    r"\bexpectEmit\b",
    r"\bassertTrue\b",
    r"\bassertFalse\b",
    r"\bassertEq\b",
    r"\bassertGt\b",
    r"\bassertGe\b",
    r"\bassertLt\b",
    r"\bassertLe\b",
    r"\brevert\s*\(",
]
ASSERT_RE = re.compile("|".join(ASSERT_PATTERNS))

# Patterns for detecting issues
EXPECT_REVERT_BARE_RE = re.compile(r"\bvm\.expectRevert\s*\(\s*\)\s*;", re.M)
EXPECT_REVERT_STRING_RE = re.compile(r'\bvm\.expectRevert\s*\(\s*"[^"]*"\s*\)\s*;', re.M)
BULLOAK_SEPARATOR_RE = re.compile(r"BULLOAK AUTOGENERATED SEPARATOR")
TODO_FIXME_RE = re.compile(r"\b(TODO|FIXME|XXX|HACK)\b", re.I)

# Tree parsing regex
TREE_NODE_RE = re.compile(r"^(?P<indent>[\s\u2502]*)(?P<edge>\u251c\u2500\u2500|\u2514\u2500\u2500)\s+(?P<text>.*)$")

# Standard test functions/modifiers to skip when checking for orphans
SKIP_TEST_PREFIXES = ("test_receive_",)
SKIP_TEST_NAMES = {"test_setUp"}
SKIP_MODIFIER_NAMES = {"setUp"}


def fail(msg: str, errors: List[str]) -> None:
    errors.append(msg)


def warn(msg: str, warnings: List[str]) -> None:
    warnings.append(msg)


def strip_comments(s: str) -> str:
    """Strip single-line and block comments from Solidity source."""
    s = re.sub(r"//.*", "", s)
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)
    return s


# ---------------------------------------------------------------------------
# Brace-matched block iteration (shared by functions and modifiers)
# ---------------------------------------------------------------------------

def _iter_blocks(text: str, pattern: re.Pattern) -> Tuple[str, str, int]:
    """Yield (name, body, line) for Solidity blocks matched by pattern.

    The pattern must capture the block name in group(1) and end at the
    opening brace.
    """
    i = 0
    while True:
        m = pattern.search(text, i)
        if not m:
            break
        name = m.group(1)
        start = m.start()
        brace_start = m.end() - 1
        depth = 0
        j = brace_start
        while j < len(text):
            if text[j] == '{':
                depth += 1
            elif text[j] == '}':
                depth -= 1
                if depth == 0:
                    break
            j += 1
        if depth != 0:
            i = brace_start + 1
            continue
        body = text[brace_start + 1:j]
        line = text[:start].count("\n") + 1
        yield name, body, line
        i = j + 1


_FUNCTION_RE = re.compile(
    r"\bfunction\s+([A-Za-z0-9_]+)\s*\([^)]*\)\s*"
    r"(?:external|public|internal|private|view|pure|payable|virtual|override|\s|[A-Za-z0-9_]+)*\{",
    re.S,
)
_MODIFIER_RE = re.compile(
    r"\bmodifier\s+([A-Za-z0-9_]+)\s*\([^;]*\)\s*\{",
    re.S,
)


def iter_functions(text: str):
    """Yield (name, body, line) for each function in text."""
    yield from _iter_blocks(text, _FUNCTION_RE)


def iter_modifiers(text: str):
    """Yield (name, body, line) for each modifier in text."""
    yield from _iter_blocks(text, _MODIFIER_RE)


# ---------------------------------------------------------------------------
# Tree parsing
# ---------------------------------------------------------------------------

def _parse_tree_nodes(path: Path) -> List[Tuple[int, int, str]]:
    """Parse a .tree file and return list of (line_index, indent, text) nodes."""
    nodes = []
    for idx, line in enumerate(path.read_text().splitlines()):
        m = TREE_NODE_RE.match(line)
        if not m:
            continue
        indent = len(m.group("indent"))
        text = m.group("text").strip()
        nodes.append((idx, indent, text))
    return nodes


def _has_children(nodes: List[Tuple[int, int, str]], i: int) -> bool:
    """Return True if the node at index i has a deeper-indented successor."""
    _, indent, _ = nodes[i]
    if i + 1 < len(nodes):
        _, next_indent, _ = nodes[i + 1]
        return next_indent > indent
    return False


def parse_tree_leaves(path: Path) -> List[Tuple[int, str]]:
    """Return (1-based line, text) for each leaf node in a .tree file."""
    nodes = _parse_tree_nodes(path)
    return [
        (idx + 1, text)
        for i, (idx, _, text) in enumerate(nodes)
        if not _has_children(nodes, i)
    ]


def parse_tree_branches(path: Path) -> List[Tuple[int, str]]:
    """Return (1-based line, text) for each non-leaf branch node in a .tree file."""
    nodes = _parse_tree_nodes(path)
    return [
        (idx + 1, text)
        for i, (idx, _, text) in enumerate(nodes)
        if _has_children(nodes, i) and not text.lower().startswith("it ")
    ]


def tree_text_to_modifier_name(text: str) -> str:
    """Convert tree branch text to expected modifier name.

    Example: "when the caller is the EntryPoint or self" -> "whenTheCallerIsTheEntryPointOrSelf"
    """
    words = text.split()
    if not words:
        return ""
    result = words[0].lower() + "".join(w.capitalize() for w in words[1:])
    return re.sub(r'[^a-zA-Z0-9]', '', result)


def get_sol_modifiers(sol_path: Path) -> List[Tuple[str, int]]:
    """Extract modifier names and line numbers from a .t.sol file."""
    return [(name, line) for name, _, line in iter_modifiers(sol_path.read_text())]


# ---------------------------------------------------------------------------
# Fuzzy name matching (shared by orphan test and orphan modifier checks)
# ---------------------------------------------------------------------------

def normalize_name(name: str) -> str:
    """Normalize a name for comparison (lowercase, remove underscores)."""
    return name.lower().replace("_", "")


def extract_key_words(name: str) -> Set[str]:
    """Extract significant words from a function/modifier name."""
    name = re.sub(r'^test_?', '', name, flags=re.I)
    words = re.findall(r'[A-Z][a-z]*|[a-z]+|\d+', name)
    stopwords = {'the', 'is', 'a', 'an', 'and', 'or', 'for', 'to', 'in', 'of', 'when', 'given', 'then'}
    return {w.lower() for w in words if len(w) > 2 and w.lower() not in stopwords}


def _fuzzy_name_match(
    actual_name: str,
    expected_names: Set[str],
    check_prefix: bool = False,
) -> bool:
    """Return True if actual_name fuzzy-matches any name in expected_names.

    When check_prefix is True, long normalized names are also compared by prefix.
    """
    norm_actual = normalize_name(actual_name)

    # Direct normalized match
    if any(normalize_name(exp) == norm_actual for exp in expected_names):
        return True

    # Keyword overlap
    actual_words = extract_key_words(actual_name)
    if not actual_words:
        return False

    for expected in expected_names:
        expected_words = extract_key_words(expected)
        common = actual_words & expected_words
        if len(common) >= len(actual_words) * 0.6:
            return True
        if expected_words and len(common) >= len(expected_words) * 0.6:
            return True

        # Normalized string containment
        norm_expected = normalize_name(expected)
        if norm_actual in norm_expected or norm_expected in norm_actual:
            return True

        # Prefix match for long names
        if check_prefix:
            min_len = min(len(norm_actual), len(norm_expected))
            if min_len > 20 and norm_actual[:min_len - 10] == norm_expected[:min_len - 10]:
                return True

    return False


# ---------------------------------------------------------------------------
# Tree <-> sol file resolution
# ---------------------------------------------------------------------------

def find_matching_tree_file(sol_path: Path) -> Path | None:
    """Find the .tree file that corresponds to a .t.sol file."""
    stem = sol_path.stem
    if stem.endswith(".t"):
        tree_path = sol_path.parent / f"{stem[:-2]}.tree"
        if tree_path.exists():
            return tree_path
    return None


def extract_abstract_contract_name(sol_path: Path) -> str | None:
    """Extract the abstract contract name from a .t.sol file."""
    m = re.search(r"abstract\s+contract\s+([A-Za-z0-9_]+)\s+is", sol_path.read_text())
    return m.group(1) if m else None


def find_tree_by_contract_name(contract_name: str) -> Path | None:
    """Find a .tree file by its contract name (first line)."""
    for tree_path in BTT_DIR.glob("*.tree"):
        first_line = tree_path.read_text().splitlines()[0].strip()
        if first_line == contract_name:
            return tree_path
    return None


def _resolve_tree_file(sol_path: Path) -> Path | None:
    """Resolve the .tree file for a given .t.sol file (try direct match, then contract name)."""
    tree_path = find_matching_tree_file(sol_path)
    if tree_path:
        return tree_path
    contract_name = extract_abstract_contract_name(sol_path)
    if contract_name:
        return find_tree_by_contract_name(contract_name)
    return None


# ---------------------------------------------------------------------------
# Orphan detection
# ---------------------------------------------------------------------------

def get_expected_functions_from_bulloak(tree_path: Path) -> Set[str]:
    """Run bulloak scaffold and extract expected function names."""
    try:
        result = subprocess.run(
            ["bulloak", "scaffold", str(tree_path), "--solidity-version", "^0.8.0"],
            capture_output=True,
            text=True,
            cwd=ROOT,
        )
        return {
            m.group(1)
            for m in re.finditer(r"\bfunction\s+(test_[A-Za-z0-9_]+)\s*\(", result.stdout)
        }
    except Exception:
        return set()


def get_sol_test_functions(sol_path: Path) -> List[Tuple[str, int]]:
    """Extract test function names from a .t.sol file."""
    text = sol_path.read_text()
    return [
        (m.group(1), text[:m.start()].count("\n") + 1)
        for m in re.finditer(r"\bfunction\s+(test_[A-Za-z0-9_]+)\s*\(", text)
    ]


def check_orphan_tests() -> Dict[Path, List[Tuple[str, int]]]:
    """Check for test functions that don't have corresponding tree leaves."""
    orphans: Dict[Path, List[Tuple[str, int]]] = {}

    for sol_path in sorted(BTT_DIR.glob("*.t.sol")):
        tree_path = _resolve_tree_file(sol_path)
        if not tree_path:
            continue

        expected_functions = get_expected_functions_from_bulloak(tree_path)
        if not expected_functions:
            continue

        file_orphans = [
            (name, line)
            for name, line in get_sol_test_functions(sol_path)
            if name not in SKIP_TEST_NAMES
            and not any(name.startswith(p) for p in SKIP_TEST_PREFIXES)
            and not _fuzzy_name_match(name, expected_functions, check_prefix=True)
        ]
        if file_orphans:
            orphans[sol_path] = file_orphans

    return orphans


def check_orphan_modifiers() -> Dict[Path, List[Tuple[str, int]]]:
    """Check for modifiers that don't have corresponding tree branches."""
    orphans: Dict[Path, List[Tuple[str, int]]] = {}

    for sol_path in sorted(BTT_DIR.glob("*.t.sol")):
        tree_path = _resolve_tree_file(sol_path)
        if not tree_path:
            continue

        expected_modifiers = {tree_text_to_modifier_name(text) for _, text in parse_tree_branches(tree_path)}
        if not expected_modifiers:
            continue

        file_orphans = [
            (name, line)
            for name, line in get_sol_modifiers(sol_path)
            if name not in SKIP_MODIFIER_NAMES
            and not _fuzzy_name_match(name, expected_modifiers)
        ]
        if file_orphans:
            orphans[sol_path] = file_orphans

    return orphans


# ---------------------------------------------------------------------------
# Bulloak
# ---------------------------------------------------------------------------

def shutil_which(cmd: str) -> str | None:
    """Locate an executable on PATH (like shutil.which without importing shutil)."""
    for p in os.environ.get("PATH", "").split(os.pathsep):
        candidate = Path(p) / cmd
        if candidate.exists() and os.access(candidate, os.X_OK):
            return str(candidate)
    return None


def check_bulloak() -> Tuple[bool, str | None]:
    if not shutil_which("bulloak"):
        return False, "bulloak not found in PATH"
    try:
        subprocess.check_call(["bulloak", "check", "test/btt/*.tree"], cwd=ROOT)
        return True, None
    except subprocess.CalledProcessError as e:
        return False, f"bulloak check failed: {e}"


def count_test_functions(text: str) -> Dict[str, List[int]]:
    """Return a mapping of test function names to the lines where they appear."""
    counts: Dict[str, List[int]] = {}
    for name, _, line in iter_functions(text):
        if name.startswith("test_"):
            counts.setdefault(name, []).append(line)
    return counts


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description="Strict BTT rule checker")
    parser.add_argument("--skip-bulloak", action="store_true", help="skip bulloak check")
    parser.add_argument("--verbose", "-v", action="store_true", help="show warnings too")
    args = parser.parse_args()

    errors: List[str] = []
    warnings: List[str] = []

    # RULE 1: Bulloak check must pass (tree-to-test synchronization)
    if not args.skip_bulloak:
        ok, msg = check_bulloak()
        if not ok:
            fail(f"bulloak: {msg}", errors)

    # RULE 2: No bulloak separators in final code
    for path in BTT_DIR.rglob("*"):
        if path.is_file() and path.suffix in {".t.sol", ".tree"}:
            text = path.read_text()
            if BULLOAK_SEPARATOR_RE.search(text):
                fail(f"bulloak separator present: {path.relative_to(ROOT)}", errors)

    # RULE 3: Tree leaves must be specific (no vague "it should revert")
    vague_leaf_re = re.compile(r"^it should revert\.?$", re.I)
    vague_revert_re = re.compile(r"it should revert", re.I)
    for tree_path in BTT_DIR.glob("*.tree"):
        for line, text in parse_tree_leaves(tree_path):
            if vague_leaf_re.match(text) or (vague_revert_re.search(text) and "with" not in text.lower()):
                fail(f"vague leaf in {tree_path.relative_to(ROOT)}:{line}: '{text}'", errors)

    # RULE 4: No bare vm.expectRevert() - must specify error selector
    for path in BTT_DIR.glob("*.t.sol"):
        text = path.read_text()
        if EXPECT_REVERT_BARE_RE.search(text):
            fail(f"bare vm.expectRevert() in {path.relative_to(ROOT)}", errors)

    # RULE 4b: No string-based vm.expectRevert() - must use .selector
    for path in BTT_DIR.glob("*.t.sol"):
        text = path.read_text()
        for match in EXPECT_REVERT_STRING_RE.finditer(text):
            line_num = text[:match.start()].count("\n") + 1
            fail(f"string-based vm.expectRevert() in {path.relative_to(ROOT)}:{line_num} - use ErrorName.selector instead", errors)

    # RULE 5: Modifiers cannot contain assertions (setup only)
    for path in BTT_DIR.glob("*.t.sol"):
        text = path.read_text()
        for name, body, line in iter_modifiers(text):
            body_no_comments = strip_comments(body)
            if ASSERT_RE.search(body_no_comments):
                fail(f"modifier contains assertion: {path.relative_to(ROOT)}:{line} {name}", errors)

    # RULE 6: Modifiers must set up state (unless explicitly ignored)
    ignore_empty_re = re.compile(r"//\s*ignore-empty-modifier\s*:\s*(.+)", re.I)
    for path in BTT_DIR.glob("*.t.sol"):
        text = path.read_text()
        for name, body, line in iter_modifiers(text):
            body_no_comments = strip_comments(body)
            body_stripped = body_no_comments.replace(" ", "").replace("\n", "").replace("\t", "")
            is_comment_only = body_stripped == ""
            is_noop = body_stripped in {"_;", "_"}
            if is_comment_only or is_noop:
                ignore_match = ignore_empty_re.search(body)
                if ignore_match:
                    reason = ignore_match.group(1).strip()
                    warn(f"empty modifier (ignored: {reason}): {path.relative_to(ROOT)}:{line} {name}", warnings)
                elif is_comment_only:
                    fail(f"comment-only modifier (does nothing): {path.relative_to(ROOT)}:{line} {name}", errors)
                else:
                    fail(f"empty modifier (does nothing): {path.relative_to(ROOT)}:{line} {name}", errors)

    # RULE 7: Tests must assert something, no comment-only tests, no loops
    loop_re = re.compile(r"\b(for|while)\s*\(")
    for path in BTT_DIR.glob("*.t.sol"):
        text = path.read_text()
        for name, body, line in iter_functions(text):
            if not name.startswith("test_"):
                continue
            body_no_comments = strip_comments(body)
            if body_no_comments.strip() == "":
                fail(f"comment-only test: {path.relative_to(ROOT)}:{line} {name}", errors)
                continue
            if not ASSERT_RE.search(body_no_comments):
                fail(f"test has no assertions: {path.relative_to(ROOT)}:{line} {name}", errors)
            if loop_re.search(body_no_comments):
                fail(f"loop inside test: {path.relative_to(ROOT)}:{line} {name}", errors)

    # RULE 8: Every .tree file must have a corresponding .t.sol file
    for tree_path in BTT_DIR.glob("*.tree"):
        sol_path = tree_path.with_suffix(".t.sol")
        if not sol_path.exists():
            fail(f"missing test file for {tree_path.relative_to(ROOT)}: expected {sol_path.name}", errors)

    # RULE 9: No duplicate test function names within a file
    for path in BTT_DIR.glob("*.t.sol"):
        text = path.read_text()
        counts = count_test_functions(text)
        for name, lines in counts.items():
            if len(lines) > 1:
                fail(f"duplicate test function: {path.relative_to(ROOT)} {name} at lines {lines}", errors)

    # RULE 10: No TODO/FIXME in test function bodies (tests should be complete)
    for path in BTT_DIR.glob("*.t.sol"):
        text = path.read_text()
        for name, body, line in iter_functions(text):
            if not name.startswith("test_"):
                continue
            if TODO_FIXME_RE.search(body):
                warn(f"TODO/FIXME in test: {path.relative_to(ROOT)}:{line} {name}", warnings)

    # RULE 11: No orphan tests (tests must have corresponding tree branches)
    if not args.skip_bulloak:
        orphans = check_orphan_tests()
        for sol_path, funcs in orphans.items():
            for func_name, line_num in funcs:
                fail(f"orphan test (no tree branch): {sol_path.relative_to(ROOT)}:{line_num} {func_name}", errors)

    # RULE 12: No orphan modifiers (modifiers must have corresponding tree branches)
    orphan_modifiers = check_orphan_modifiers()
    for sol_path, mods in orphan_modifiers.items():
        for modifier_name, line_num in mods:
            warn(f"orphan modifier (no tree branch): {sol_path.relative_to(ROOT)}:{line_num} {modifier_name}", warnings)

    # Output results
    if args.verbose and warnings:
        print("WARNINGS:")
        for w in warnings:
            print(f"  - {w}")
        print()

    if errors:
        print("BTT CHECK FAILED")
        for e in errors:
            print(f"- {e}")
        sys.exit(1)

    print("BTT CHECK PASSED")
    if warnings and not args.verbose:
        print(f"({len(warnings)} warnings - use -v to see)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
